# Generated by Django 3.2.22 on 2024-01-13 15:41

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(
                default='IE', max_length=2),
            preserve_default=False,
        ),
    ]
